basePath: /
definitions:
  dto.GetItemResponse:
    properties:
      createdAt:
        type: string
      description:
        type: string
      itemCode:
        type: string
      itemId:
        type: integer
      orderId:
        type: integer
      quantity:
        type: integer
      updatedAt:
        type: string
    type: object
  dto.GetOrdersResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/dto.OrderWithItems'
        type: array
      message:
        type: string
      statusCode:
        type: integer
    type: object
  dto.NewItemRequest:
    properties:
      description:
        example: Indomie Goreng
        type: string
      itemCode:
        example: indomiegr
        type: string
      quantity:
        example: 2
        type: integer
    type: object
  dto.NewOrderRequest:
    properties:
      customerName:
        example: An Yujin
        type: string
      items:
        items:
          $ref: '#/definitions/dto.NewItemRequest'
        type: array
      orderedAt:
        example: "2023-09-22T09:11:00+07:00"
        type: string
    type: object
  dto.NewOrderResponse:
    properties:
      data: {}
      message:
        type: string
      statusCode:
        type: integer
    type: object
  dto.OrderWithItems:
    properties:
      createdAt:
        type: string
      customerName:
        type: string
      items:
        items:
          $ref: '#/definitions/dto.GetItemResponse'
        type: array
      orderId:
        type: integer
      orderedAt:
        type: string
      updatedAt:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: yusrililham@gmail.com
    name: Yusril Ilham Kholid
    url: http://github.com/yusrililhm
  description: Tugas ke 2 Kampus Merdeka
  title: Order API Specs
  version: "1.0"
paths:
  /orders:
    get:
      consumes:
      - application/json
      description: Get all orders
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.GetOrdersResponse'
      summary: Fetch order
      tags:
      - Orders
    post:
      consumes:
      - application/json
      description: Create new orders
      parameters:
      - description: body request for create new order
        in: body
        name: dto.NewOrderRequest
        required: true
        schema:
          $ref: '#/definitions/dto.NewOrderRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.NewOrderResponse'
      summary: Create new order
      tags:
      - Orders
  /orders/{orderId}:
    delete:
      consumes:
      - application/json
      description: Delete order by order id
      parameters:
      - description: order id
        in: path
        name: orderId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Remove order
      tags:
      - Orders
    put:
      consumes:
      - application/json
      description: Update order by order id
      parameters:
      - description: order id
        in: path
        name: orderId
        required: true
        type: integer
      - description: update order body request
        in: body
        name: dto.NewOrderRequest
        required: true
        schema:
          $ref: '#/definitions/dto.NewOrderRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.NewOrderResponse'
      summary: Edit order
      tags:
      - Orders
swagger: "2.0"
